### PR TITLE
make the middleware respond to composeExtension/fetchTask

### PR DESCRIPTION
**Pull request by tdwhite0**
I've been using this in an app that uses the preview Teams features and I needed a way to respond to composeExtension/fetchTask. I wasn't sure exactly what the typescript types should be yet but I thought I'd get your feedback.

### CODE REVIEW

**Comment by wictorwilen** [comment]
Good stuff! Will merge as soon as possible

**Comment by wictorwilen** [comment]
@tdwhite0 - this is now merged. Did some smaller changes to the implementation. Check the README.md file for implementation details.

**Comment by tdwhite0** [comment]
Nice, I see composeExtension/onCardButtonClicked got in there too.

**Comment by wictorwilen** [comment]
@tdwhite0 - yup, added it even though it lacks official documentation. But it's a great feature. If you're using the Yeoman Teams generator, all you should have to do now is to update the express host feature: `npm install express-msteams-host@preview --save`

**Pull request merged**
